### PR TITLE
Fix #194 and #15. Use world coordinates for synchronization.

### LINKED ISSUE #194: Sync Volumes does not work with coordinate input
In the volume viewer, when "Sync Volumes" is checked, only mouse input is synchronized. When the voxel/world coordinates are changed using the keyboard via editing the textboxes below the volumes, only the one volume is updated and the rest are unmodified.

### PR DESCRIPTION
**Pull request by rdvincent**
This pull request is bigger than I might have liked, but solving the main issue (#15) required a major rethinking of how we handle the overlay volume.

To make synchronization work in world coordinates, we need a voxel-to-world and world-to-voxel transform for every potentially synced volume. This means the overlay needs these transforms. The overlay uses a simple, default MINC transform. This now gives the overlay volume most of the properties and methods formerly associated only with the MINC and NIfTI-1 volumes.

I did a little code cleanup while I was at it. Fixing #194 was easy once this was working.

### CODE REVIEW

File: src/brainbrowser/volume-viewer/modules/loading.js [hunk 1]
```diff
@@ -344,6 +344,22 @@ BrainBrowser.VolumeViewer.modules.loading = function(viewer) {
     default_panel_height = height;
   };
 
+  viewer.syncPosition = function(panel, volume, axis_name) {
+    var wc = volume.getWorldCoords();
+    viewer.volumes.forEach(function(synced_volume) {
+      if (synced_volume !== volume) {
```
Comment (natacha-beck) [inline src/brainbrowser/volume-viewer/modules/loading.js]: Maybe you can directly return: 
if (synced_volume === volume) return ;
